import Navbar from "@/Components/Shared/Navbar/Navbar";
import "./globals.css";
import { Saira } from "next/font/google";
import Footer from "@/Components/Shared/Footer/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/Context/authContext/AuthProvider";
import "react-datepicker/dist/react-datepicker.css";
import { ChatContextProvider } from "./Context/context";

const inter = Saira({ subsets: ["latin"] });

export const metadata = {
  title: "Ed_Nexus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div>

          <ChatContextProvider>
            <AuthProvider>
              <Navbar />
              <main className="">
                {children}
                <ToastContainer
                  position="top-right"
                  autoClose={5000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick
                  rtl={false}
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="light"
                />
                <ToastContainer />
              </main>
            </AuthProvider>



            <Footer />
          </ChatContextProvider>
        </div>
      </body>
    </html>
  );
}
